
CREATE TABLE "JCMA"."POST"
(
   ID bigint PRIMARY KEY NOT NULL,
   CONTENT clob(255) NOT NULL,
   TITLE varchar(255) NOT NULL,
   AUTHOR_ID bigint NOT NULL
)
;
CREATE TABLE "JCMA"."POST_ID_SEQUENCE"
(
   NEXT_VAL bigint
)
;
CREATE TABLE "JCMA"."SETTING"
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   VALUE varchar(255)
)
;
CREATE TABLE "JCMA"."USERS"
(
   ID bigint PRIMARY KEY NOT NULL,
   EMAIL varchar(255) NOT NULL,
   FIRSTNAME varchar(255) NOT NULL,
   LASTNAME varchar(255) NOT NULL
)
;
CREATE TABLE "JCMA"."USERS_ID_SEQUENCE"
(
   NEXT_VAL bigint
)
;
ALTER TABLE "JCMA"."POST"
ADD CONSTRAINT FK___POST___AUTHOR
FOREIGN KEY (AUTHOR_ID)
REFERENCES "JCMA"."USERS"(ID)
;
CREATE INDEX SQL121010153015810 ON "JCMA"."POST"(AUTHOR_ID)
;
CREATE UNIQUE INDEX SQL121010153015100 ON "JCMA"."POST"(ID)
;
CREATE UNIQUE INDEX SQL121010153015360 ON "JCMA"."SETTING"(ID)
;
CREATE UNIQUE INDEX SQL121010153015541 ON "JCMA"."USERS"(EMAIL)
;
CREATE UNIQUE INDEX SQL121010153015540 ON "JCMA"."USERS"(ID)
;
